name: 'Conventional Release Automator'
description: 'Automated release workflow with conventional commits and changelog generation'
author: hsayed

inputs:
  version:
    description: 'Semver bump type'
    required: true
    type: choice
    options: [patch, minor, major]
    default: patch
  include-non-conventional:
    description: 'Include non-conventional commits in release notes'
    required: false
    default: false
    type: boolean
  files-pattern:
    description: 'Extra files to upload (glob, e.g. dist/*.zip)'
    required: false
    default: ''
    type: string
  publish-vsce:
    description: 'Publish to VS Code Marketplace'
    required: false
    default: false
    type: boolean
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '24'

outputs:
  version:
    description: 'The version that was released'
    value: ${{ steps.release.outputs.version }}
  tag:
    description: 'The git tag that was created'
    value: ${{ steps.release.outputs.tag }}
  release-url:
    description: 'The URL of the created GitHub release'
    value: ${{ steps.release.outputs.release-url }}

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}

    - name: Configure Git identity
      shell: bash
      run: |
        git config user.name  "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Save rollback info
      id: rollback-save
      shell: bash
      run: |
        echo "previous-commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    - name: Bump version & create tag
      id: bump
      shell: bash
      run: |
        npm version ${{ inputs.version }} -m "chore: release %s"
        echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

    - name: Push commit & tag
      shell: bash
      run: git push origin HEAD --follow-tags

    # - name: Install dependencies
    #   shell: bash
    #   run: npm ci

    # - name: Build extension
    #   shell: bash
    #   run: npm run build
    #   continue-on-error: true

    - name: Publish & package extension
      if: ${{ inputs.publish-vsce == 'true' }}
      id: publish
      uses: HaaLeo/publish-vscode-extension@v2
      with:
        pat:         ${{ secrets.VSCE_PAT }}
        registryUrl: https://marketplace.visualstudio.com

    - name: Write changelog config
      env:
        INCLUDE_NON_CONV: ${{ inputs.include-non-conventional }}
        REPO_URL:         ${{ github.server_url }}/${{ github.repository }}
      shell: bash
      run: |
        python3 << 'PYEOF'
        import json, os

        include_non_conv = os.environ.get("INCLUDE_NON_CONV", "false").lower() == "true"
        repo             = os.environ.get("REPO_URL", "")

        CONV = r"^.{0,6}(?!chore:\s*release)(feat|fix|chore|docs|style|refactor|perf|test|build|ci|revert):"
        ALL  = r"^(?!.{0,6}chore:\s*release)"

        config = {
          "categories": [
            {
              "title": "## What's Changed",
              "rules": [{"pattern": ALL if include_non_conv else CONV, "on_property": "title"}]
            }
          ],
          "ignore_labels": ["ignore"],
          "sort": {"order": "DESC", "on_property": "mergedAt"},
          "template":      "#{{CHANGELOG}}\n\n**Full Changelog**: [`#{{FROM_TAG}}...#{{TO_TAG}}`](" + repo + "/compare/#{{FROM_TAG}}...#{{TO_TAG}})",
          "pr_template":   "- #{{TITLE}} by @#{{AUTHOR}} ([`#{{MERGE_SHA}}`](" + repo + "/commit/#{{MERGE_SHA}}))",
          "empty_template": "_No changes in this release._",
          "trim_values":    True
        }

        out = json.dumps(config, indent=2, ensure_ascii=False)
        with open(".changelog-config.json", "w") as f:
          f.write(out)
        print(out)
        PYEOF

    - name: Generate changelog
      id: changelog
      uses: mikepenz/release-changelog-builder-action@v5
      with:
        token:         ${{ secrets.GITHUB_TOKEN }}
        toTag:         ${{ steps.bump.outputs.tag }}
        configuration: .changelog-config.json
        mode:          "COMMIT"

    - name: Shorten commit hashes
      id: notes
      shell: bash
      run: |
        NOTES=$(cat << 'NOTES_EOF'
        ${{ steps.changelog.outputs.changelog }}
        NOTES_EOF
        )
        NOTES=$(echo "$NOTES" | sed -E 's/([a-f0-9]{7})[a-f0-9]{33}/\1/g')
        {
          echo "changelog<<EOF"
          echo "$NOTES"
          echo "EOF"
        } >> $GITHUB_OUTPUT

    - name: Create GitHub release
      id: release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.bump.outputs.tag }}
        body:     ${{ steps.notes.outputs.changelog }}
        files: |
          *.vsix
          ${{ inputs.files-pattern }}

    - name: Set outputs
      shell: bash
      run: |
        echo "version=$(echo ${{ steps.bump.outputs.tag }} | sed 's/v//')" >> $GITHUB_OUTPUT
        echo "tag=${{ steps.bump.outputs.tag }}" >> $GITHUB_OUTPUT
        echo "release-url=https://github.com/${{ github.repository }}/releases/tag/${{ steps.bump.outputs.tag }}" >> $GITHUB_OUTPUT

    - name: Rollback on failure
      if: failure()
      shell: bash
      run: |
        echo "::error::Release failed — rolling back tag and commit..."
        
        TAG="${{ steps.bump.outputs.tag }}"
        PREV="${{ steps.rollback-save.outputs.previous-commit }}"
        
        git push --delete origin "$TAG" 2>/dev/null || echo "Remote tag not found"
        git tag -d "$TAG" 2>/dev/null || echo "Local tag not found"
        git reset --hard "$PREV"
        git push origin HEAD --force
        
        echo "::error::Rollback complete — tag and commit have been rolled back."

branding:
  icon: 'package'
  color: 'blue'
